name: Deploy to DigitalOcean
on:
  push:
    branches: [test]

  workflow_dispatch:

jobs:

  lint:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

  build:
    runs-on: self-hosted
    needs: [lint]
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to DigitalOcean
        run: |
          echo "Building and deploying to DigitalOcean..."
          docker compose up --build -d

