name: Deploy to DigitalOcean
on:
  push:
    branches: [test]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to DigitalOcean
        run: |
          echo "Building and deploying to DigitalOcean..."
          docker compose up --build -d
          
